apiVersion: v1
kind: Secret
metadata:
  name: hubot-slack-token
type: Opaque
data:
  token: <MY_BASE64_ENCODED_SLACK_TOKEN>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: halbert
  annotations:
    keel.sh/approvals: '1'
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 5m"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: halbert
  template:
    metadata:
      labels:
        app: halbert
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: halbert
        image: jonfairbanks/halbert
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
        env:
        - name: HUBOT_SLACK_TOKEN
          valueFrom:
            secretKeyRef: 
              name: hubot-slack-token
              key: token
        volumeMounts:
          - name: logs
            mountPath: /app/logs
      volumes:
        - name: logs
          hostPath:
              path: /logs
