apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: halbert-pvc
  namespace: halbert
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
